// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230814100551_fewMoreChanges")]
    partial class fewMoreChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.BorrowerDetails", b =>
                {
                    b.Property<int>("BorrowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<int?>("LoanInformationId")
                        .HasColumnType("int");

                    b.Property<string>("MailingAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("BorrowerId");

                    b.HasIndex("LoanInformationId");

                    b.ToTable("BorrowersDetails");
                });

            modelBuilder.Entity("Domain.LoanDetails", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LoanInformationId")
                        .HasColumnType("int");

                    b.Property<decimal>("PIPmtAmt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("PmtDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PropertyAddress")
                        .HasColumnType("longtext");

                    b.Property<decimal>("RemainingPayments")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("UPBAmt")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LoanId");

                    b.HasIndex("LoanInformationId")
                        .IsUnique();

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("Domain.LoanInformation", b =>
                {
                    b.Property<int>("LoanInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Escrow")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("LoanBoardingDate")
                        .HasColumnType("date");

                    b.Property<int>("LoanTerm")
                        .HasColumnType("int");

                    b.Property<string>("LoanType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("NoteDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NoteRatePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentFreq")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryContact")
                        .HasColumnType("longtext");

                    b.Property<int>("PriorServicerLoanId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxInsurancePmtAmt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LoanInformationId");

                    b.ToTable("LoanInformation");
                });

            modelBuilder.Entity("Domain.BorrowerDetails", b =>
                {
                    b.HasOne("Domain.LoanInformation", null)
                        .WithMany("BorrowerDetails")
                        .HasForeignKey("LoanInformationId");
                });

            modelBuilder.Entity("Domain.LoanDetails", b =>
                {
                    b.HasOne("Domain.LoanInformation", "LoanInformation")
                        .WithOne("LoanDetails")
                        .HasForeignKey("Domain.LoanDetails", "LoanInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanInformation");
                });

            modelBuilder.Entity("Domain.LoanInformation", b =>
                {
                    b.Navigation("BorrowerDetails");

                    b.Navigation("LoanDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
