// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230809114232_fewMoreChanges")]
    partial class fewMoreChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Borrower_DetailsLoan_Information", b =>
                {
                    b.Property<Guid>("Borrower_DetailsBorrower_Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Loan_InformationId")
                        .HasColumnType("char(36)");

                    b.HasKey("Borrower_DetailsBorrower_Id", "Loan_InformationId");

                    b.HasIndex("Loan_InformationId");

                    b.ToTable("Borrower_DetailsLoan_Information");
                });

            modelBuilder.Entity("Domain.Borrower_Details", b =>
                {
                    b.Property<Guid>("Borrower_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Contact_Number")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Full_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Mailing_Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("Zip_code")
                        .HasColumnType("int");

                    b.HasKey("Borrower_Id");

                    b.ToTable("Borrowers");
                });

            modelBuilder.Entity("Domain.Loan_Details", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("PI_Pmt_Amt")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Pmt_Due_Date")
                        .HasColumnType("date");

                    b.Property<string>("Property_Address")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Remaining_EMI")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UPB_Amt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loan_Details");
                });

            modelBuilder.Entity("Domain.Loan_Information", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Escrow")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("Loan_Boarding_Date")
                        .HasColumnType("date");

                    b.Property<int>("Loan_Term")
                        .HasColumnType("int");

                    b.Property<int>("Loan_Type")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Note_Date")
                        .HasColumnType("date");

                    b.Property<int>("Note_Rate_Percent")
                        .HasColumnType("int");

                    b.Property<string>("Payment_Freq")
                        .HasColumnType("longtext");

                    b.Property<string>("Primary_Contact")
                        .HasColumnType("longtext");

                    b.Property<int>("Prior_Servicer_Loan_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tax_Insurance_Pmt_Amt")
                        .HasColumnType("int");

                    b.Property<int>("Total_Loan_Amount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loan_Information");
                });

            modelBuilder.Entity("Borrower_DetailsLoan_Information", b =>
                {
                    b.HasOne("Domain.Borrower_Details", null)
                        .WithMany()
                        .HasForeignKey("Borrower_DetailsBorrower_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Loan_Information", null)
                        .WithMany()
                        .HasForeignKey("Loan_InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Loan_Information", b =>
                {
                    b.HasOne("Domain.Loan_Details", "Loan_Details")
                        .WithOne("Loan_Information")
                        .HasForeignKey("Domain.Loan_Information", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan_Details");
                });

            modelBuilder.Entity("Domain.Loan_Details", b =>
                {
                    b.Navigation("Loan_Information");
                });
#pragma warning restore 612, 618
        }
    }
}
