// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.BorrowerDetails", b =>
                {
                    b.Property<int>("BorrowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MailingAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("BorrowerId");

                    b.ToTable("BorrowersDetails");
                });

            modelBuilder.Entity("Domain.LoanDetails", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LoanInformationId")
                        .HasColumnType("int");

                    b.Property<decimal>("PIPmtAmt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateOnly>("PmtDueDate")
                        .HasColumnType("date");

                    b.Property<int>("RemainingPayments")
                        .HasColumnType("int");

                    b.Property<decimal>("UPBAmt")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LoanId");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("Domain.LoanInformation", b =>
                {
                    b.Property<int>("LoanInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BorrowerId")
                        .HasColumnType("int");

                    b.Property<bool>("Escrow")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("LoanBoardingDate")
                        .HasColumnType("date");

                    b.Property<int>("LoanTerm")
                        .HasColumnType("int");

                    b.Property<string>("LoanType")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("NoteDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NoteRatePercent")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentFreq")
                        .HasColumnType("longtext");

                    b.Property<int>("PriorServicerLoanId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TaxInsurancePmtAmt")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("LoanInformationId");

                    b.ToTable("LoanInformation");
                });

            modelBuilder.Entity("Domain.Payment_Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Due_Date")
                        .HasColumnType("date");

                    b.Property<string>("Frequency")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Insurance_Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Interest_Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Loan_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Monthly_Payment_Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Note_Interest_Rate")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Principal_Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Tax_Amount")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalLoanAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UPB_Amount")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Payment_Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
